### ISSUE TITLE
TwirlCompiler fails to lookup scala-*.jar on Windows 2003

### ISSUE THREAD

**Issue by gseitz** [spray/twirl#10]
Hi,

There's a bug in the Play framework template compiler, that causes it to fail to properly lookup `scala-library.jar` and `scala-compiler.jar`.
The corresponding ticket for @playframework is [ticket-944](https://play.lighthouseapp.com/projects/82401-play-20/tickets/944-scalatemplatecompiler-fails-to-lookup-scala-libraryjar-on-windows-xp) in their issue tracker. The fix is planned for Play 2.1.1.
(The ticket title mentions Windows XP, but that's a type and should be Windows 2003.)
You can find the fix in my fork of Play20 in [this commit](https://github.com/gseitz/Play20/commit/533b6342777465764660d5b7ab5336550bdd5504), which applies to `TemplateCompiler` in Twirl as well.

Our build server runs on Windows 2003, and I already have to maintain an internal fork of Play20, which works as expected with the aforementioned fix.

Best regards

**Comment by jrudolph** [comment]
Thanks @gseitz for the report (and sorry for the late response). This got fixed by synchronizing with a more current play version (see #16) which incorporates your fix.
