### ISSUE TITLE
Support for scala v2.10

### ISSUE THREAD

**Issue by magnusart** [spray/twirl#13]
Hi

We're unable to use the Twirl plugin. I get the following error:
Unresolved dependencies: io.spray#twirl-api_2.10;0.6.2

I have tried to go back to an earlier version:
libraryDependencies += sbtPluginExtra(
  m = "io.spray" % "sbt-twirl" % "0.6.2", // Plugin module name and version
  sbtV = "0.12",    // SBT version
  scalaV = "2.9.2"    // Scala version compiled the plugin
)

Still no dice. Could you please release a 2.10 build into repos?

**Comment by jrudolph** [comment]
Actually, the artifacts are all there but there's a bug in the twirl sbt-plugin. I will release a fix ASAP.

**Comment by magnusart** [comment]
Oh, OK.

I had a look here: http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/io.spray/sbt-twirl/ and could not find 2.10 so I thought that was the issue.

**Comment by jrudolph** [comment]
For the record: while this is not fixed you can still use 0.6.1 which is practically identical.

**Comment by magnusart** [comment]
Thanks for the answer, I've had some other things on my plate the last weeks (including vacation). I'll have another look at this soon. 

But just to make sure I understand you: 
I thought that the problem was that there was not 2.10 build in the repo as I get 404 when building. 
1. Are you're saying that a Scala 2.10 version is actually there for SBT to pick up for version 0.6.1 (I can't find it)?
2. Or are you saying I should be able to install it by lowering the my scala version to 2.9 and picking 0.6.1 instead of 0.6.2 like I described above in my previous comment?

In case of number two, which I would see as a way forward for the time being, would you consider releasing perhaps a snapshot version for 2.10 of 0.6.2?

By the way, thanks for for packaging twirl in the first place! :+1:

**Comment by jrudolph** [comment]
The situation for 0.6.1 is this:
- it should work with both Scala 2.9.x and 2.10.x
- there are no maven artifacts for the sbt parts and the compiler

0.6.2 should have added maven artifacts but is broken.

So, what is the error you are experiencing with 0.6.1?

**Comment by magnusart** [comment]
Hi, with 0.6.1 SBT resolves fine now right now. I just hadn't had a chance to give it a try yet.
