### ISSUE TITLE
Be sure that you are up to date with latest improvements and fixes applied to Play

### ISSUE THREAD

**Issue by julienrf** [spray/twirl#20]
Please consider backporting patches like e.g.: playframework/playframework#2151

**Comment by jrudolph** [comment]
This version of twirl will be replaced by https://github.com/playframework/twirl in the near future. It seems the particular bugfix came in right after the last sync with upstream. If you are able to update to sbt 0.13.5, could you try to use the playframework version?

**Comment by julienrf** [comment]
Yes, that’s fine, I didn’t notice that I was on the wrong repository.
