### ISSUE TITLE
Instructions to use Twirl as a stand-alone compiler

### ISSUE THREAD

**Issue by ahtik** [spray/twirl#23]
Twirl headline says "stand-alone and packaged as an SBT plugin".

As of today is it possible to run twirl compiler as a stand-alone task without SBT dependency?

**Comment by ahtik** [comment]
Actually, https://github.com/playframework/twirl/issues is possibly a better place for this question. Also likely not relevant as "stand-alone" looks to imply being independent from spray or playframework.

There doesn't seem to be support for being independent from SBT. Sorry about the noise.

**Comment by jrudolph** [comment]
> Also likely not relevant as "stand-alone" looks to imply being independent from spray or playframework.

Yes, exactly.
