### ISSUE TITLE
Support includes

### ISSUE THREAD

**Issue by analytically** [spray/twirl#6]
Currently twirl does not support includes, as like the Play documentation:

Again, there’s nothing special here. You can just call any other template you like (and in fact any other function coming from anywhere at all):

<h1>Home</h1>
 

<div id="side">
  @common.sideBar()
</div>

**Comment by sirthias** [comment]
No, twirl supports includes.
Check out this example for the spray site:
https://github.com/spray/spray/blob/master/site/src/main/twirl/header.scala.html#L24

**Comment by analytically** [comment]
Have you tried using subdirectories? e.g. elements/jquery.scala.html -> @html.elements.jquery()

**Comment by sirthias** [comment]
Check out this section of the README:
https://github.com/spray/twirl#package-names

Twirl handles sub-packages differently from the play engine. Try `elements.html.jquery()`.

**Comment by analytically** [comment]
Damn sorry for the noise. The package paragraph should include an example of an include.
