### ISSUE TITLE
ivy.xml contains wrong sbt version and wrong scala version

### ISSUE THREAD

**Issue by AEtherSurfer** [spray/twirl#9]
[info] Resolving cc.spray#sbt-twirl;0.5.2 ...
[error]     sbt-plugin-releases: bad sbtVersion found in http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/cc.spray/sbt-twirl/scala_2.9.2/sbt_0.12/0.5.2/ivys/ivy.xml: expected='0.12' found='0.11.3'
[error]     sbt-plugin-releases: bad scalaVersion found in http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/cc.spray/sbt-twirl/scala_2.9.2/sbt_0.12/0.5.2/ivys/ivy.xml: expected='2.9.2' found='2.9.1'
[error]     sbt-plugin-releases: bad sbtVersion found in http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/cc.spray/sbt-twirl/scala_2.9.2/sbt_0.12/0.5.2/ivys/ivy.xml: expected='0.12' found='0.11.3'
[error]     sbt-plugin-releases: bad scalaVersion found in http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/cc.spray/sbt-twirl/scala_2.9.2/sbt_0.12/0.5.2/ivys/ivy.xml: expected='2.9.2' found='2.9.1'

**Comment by jrudolph** [comment]
Thanks for reporting. We accidentally pushed a broken version back then. It should be fixed in the current version, 0.6.1.

Make sure you use the new group-id as well:

```
addSbtPlugin("io.spray" % "sbt-twirl" % "0.6.1")
```
